# Generated by Django 5.1.3 on 2024-11-24 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_customerpolicy_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerpolicy',
            name='payment_status',
        ),
        migrations.AlterField(
            model_name='customerpolicy',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Purchased', 'Purchased')], default='Pending', max_length=10),
        ),
    ]
