# Generated by Django 5.1.3 on 2024-11-24 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_customerpolicy_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpolicy',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Purchased', 'Purchased')], default='pending', max_length=10),
        ),
    ]
