# Generated by Django 5.1.3 on 2024-11-27 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_claim_claimant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claim',
            old_name='claimant',
            new_name='customer',
        ),
    ]
