# Generated by Django 5.1.3 on 2024-11-28 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_claim_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='details',
            field=models.TextField(default='Default policy details'),
        ),
    ]
